AspNetCoreIdentityExample/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreIdentityExample.Controllers
{
    [Authorize]
    public class PagesController : Controller
    {
        [Authorize(Roles = "Tor")]
        public IActionResult Page1()
        {
            return View();
        }

        [Authorize(Roles = "Editor")]
        public IActionResult Page2()
        {
            return View();
        }

        [Authorize(Roles = "Moderator")]
        public IActionResult Page3()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Page4()
        {
            return View();
        }

        [Authorize(Policy = "TimeControl")]
        public IActionResult Page5()
        {
            return View();
        }

        [Authorize(Policy = "UserClaimNamePolicy")]
        public IActionResult Page6()
        {
            return View();
        }

        [Authorize(Policy = "UserClaimPositionPolicy")]
        public IActionResult Page7()
        {
            return View();
        }
    }
}

AspNetCoreIdentityExample/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreIdentityExample.Models.Authentication;
using AspNetCoreIdentityExample.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace AspNetCoreIdentityExample.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<AppRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;

        public RoleController(RoleManager<AppRole> roleManager, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View(_roleManager.Roles.ToList());
        }

        public async Task<IActionResult> CreateRole(string id)
        {
            if (id != null)
            {
                AppRole role = await _roleManager.FindByIdAsync(id);

                return View(new RoleViewModel
                {
                    Name = role.Name
                });
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(RoleViewModel model, string id)
        {
            IdentityResult result = null;
            if (id != null)
            {
                AppRole role = await _roleManager.FindByIdAsync(id);
                role.Name = model.Name;
                result = await _roleManager.UpdateAsync(role);
            }
            else
                result = await _roleManager.CreateAsync(new AppRole { Name = model.Name, OlusturulmaTarihi = DateTime.Now });

            if (result.Succeeded)
            {
                //Başarılı...
            }
            return View();
        }

        public async Task<IActionResult> DeleteRole(string id)
        {
            AppRole role = await _roleManager.FindByIdAsync(id);
            IdentityResult result = await _roleManager.DeleteAsync(role);
            if (result.Succeeded)
            {
                //Başarılı...
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RoleAssign(string id)
        {
            AppUser user = await _userManager.FindByIdAsync(id);
            List<AppRole> allRoles = _roleManager.Roles.ToList();
            List<string> userRoles = await _userManager.GetRolesAsync(user) as List<string>;
            List<RoleAssignViewModel> assignRoles = new List<RoleAssignViewModel>();
            allRoles.ForEach(role => assignRoles.Add(new RoleAssignViewModel
            {
                HasAssign = userRoles.Contains(role.Name),
                RoleId = role.Id,
                RoleName = role.Name
            }));

            return View(assignRoles);
        }

        [HttpPost]
        public async Task<ActionResult> RoleAssign(List<RoleAssignViewModel> modelList, string id)
        {
            AppUser user = await _userManager.FindByIdAsync(id);
            foreach (RoleAssignViewModel role in modelList)
            {
                if (role.HasAssign)
                    await _userManager.AddToRoleAsync(user, role.RoleName);
                else
                    await _userManager.RemoveFromRoleAsync(user, role.RoleName);
            }
            return RedirectToAction("Index", "User");
        }
    }
}

AspNetCoreIdentityExample/Controllers/TwoAuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreIdentityExample.Models.Authentication;
using AspNetCoreIdentityExample.Models.ViewModels;
using AspNetCoreIdentityExample.Servises;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreIdentityExample.Controllers
{
    public class TwoAuthenticationController : Controller
    {
        AuthenticatorService _authenticatorService;
        UserManager<AppUser> _userManager;

        public TwoAuthenticationController(AuthenticatorService authenticatorService, UserManager<AppUser> userManager)
        {
            _authenticatorService = authenticatorService;
            _userManager = userManager;
        }

        public async Task<IActionResult> SelectTwoFactorAuthentication()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SelectTwoFactorAuthentication(TwoFactorTypeSelectVM model)
        {
            switch (model.TwoFactorType)
            {
                case Models.Enums.TwoFactorType.Authenticator:
                    return RedirectToAction("AuthenticatorVerify");
                case Models.Enums.TwoFactorType.SMS:
                    return RedirectToAction("SMSVerify");
                case Models.Enums.TwoFactorType.Email:
                    return RedirectToAction("EmailVerify");
            }

            return View();
        }

        public async Task<IActionResult> AuthenticatorVerify()
        {
            AppUser user = await _userManager.FindByNameAsync(User.Identity.Name);
            string sharedKey = await _authenticatorService.GenerateSharedKey(user);
            string qrcodeUri = await _authenticatorService.GenerateQrCodeUri(sharedKey, "www.gencayyildiz.com", user);

            return View(new AuthenticatorVM
            {
                SharedKey = sharedKey,
                QrCodeUri = qrcodeUri
            });
        }

        [HttpPost]
        public async Task<IActionResult> AuthenticatorVerify(AuthenticatorVM model)
        {
            AppUser user = await _userManager.FindByNameAsync(User.Identity.Name);
            VerifyState verifyState = await _authenticatorService.Verify(model, user);
            if (verifyState.State)
            {
                TempData["message2"] = "İki adımlı doğrulama hesaba tanımlanmıştır.";
                TempData["message3"] = verifyState.RecoveryCode;
            }
            return View(model);
        }

        public async Task<IActionResult> SMSVerify()
        {
            //İlgili makalede kodlanacaktır...
            return View();
        }

        public async Task<IActionResult> EmailVerify()
        {
            //İlgili makalede kodlanacaktır...
            return View();
        }
    }
}

AspNetCoreIdentityExample/Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>

<html>
<head>
    <script src="~/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    @RenderSection("Scripts", false)
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Home">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-action="Page1" asp-controller="Pages">Page1 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-action="Page2" asp-controller="Pages">Page2 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-action="Page3" asp-controller="Pages">Page3 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-action="SelectTwoFactorAuthentication" asp-controller="TwoAuthentication">İki Adımlı Doğrulama <span class="sr-only">(current)</span></a>
            </li>

            @if (!User.Identity.IsAuthenticated)
            {
                <li class="nav-item active">
                    <a class="nav-link" asp-action="SignIn" asp-controller="User">Kaydol <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" asp-action="Index" asp-controller="User"> Giriş Yap<span class="sr-only">(current)</span></a>
                </li>
            }
            else
            {
                <li class="nav-item active">
                    <a class="nav-link" asp-action="Logout" asp-controller="User"> Çıkış Yap<span class="sr-only">(current)</span></a>
                </li>
            }
        </ul>
    </div>
</nav>
<br/>
<br/>
<br/>
<div>
    <a asp-action="Page1" asp-controller="Pages">Tor</a> |
    <a asp-action="Page2" asp-controller="Pages">Editor</a> |
    <a asp-action="Page3" asp-controller="Pages">Moderator</a> |
    <a asp-action="Page4" asp-controller="Pages">Admin</a> |
    <a asp-action="Page5" asp-controller="Pages">TimeControl policy</a>|
    <a asp-action="Page6" asp-controller="Pages">UserClaimNamePolicy policy</a> |
    <a asp-action="Page7" asp-controller="Pages">UserClaimPositionPolicy policy</a>
    <br/>
    <a asp-action="Index" asp-controller="User">Index</a> |
    <a asp-action="Signin" asp-controller="User">Signin</a> |
    @if (User.Identity.IsAuthenticated)
    {
        <a asp-action="Index" asp-controller="Role">Roles</a>
        @: |

        <a asp-action="Profile" asp-controller="User">Profile</a>
        @: |

        <a asp-action="Logout" asp-controller="User" asp-route-returnUrl="/User/Signin">Logout</a>
    }
    else
    {
        <a asp-action="Login" asp-controller="User">Login</a>
        @: |
    }

    <br/>
    @RenderBody()
</div>
</body>
</html>

AspNetCoreIdentityExample/Views/Shared/_ScriptPartial.cshtml
<script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script src="~/qrcode.min.js"></script>